name: GitHub Pages deploy
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    deploy:
        name: Deploy GitHub Pages site
        uses: "actions/deploy-pages@v4.0.5"
